/**
 * Offline outbox for chat messages, backed by IndexedDB.
 *
 * Each entry is keyed by `clientId` (a UUID generated by the sender).
 * The server's clientId-based idempotency (unique index on {sender, clientId})
 * makes replays safe — the same outbox entry can be retried any number of times
 * without duplicating the message in the database.
 *
 * The outbox survives reloads and is hydrated into the messages cache on startup.
 */

const DB_NAME = "aetherchat-outbox";
const DB_VERSION = 1;
const STORE = "messages";

export type OutboxEntry = {
  clientId: string;
  chatId: string;
  content: string;
  type: "text" | "image" | "file";
  createdAt: number;
  attempts: number;
  lastError?: string;
  /* `pending` = still trying. `failed` = give up, surface to user. */
  status: "pending" | "failed";
};

let dbPromise: Promise<IDBDatabase> | null = null;

function openDB(): Promise<IDBDatabase> {
  if (dbPromise) return dbPromise;

  dbPromise = new Promise<IDBDatabase>((resolve, reject) => {
    /* SSR / older browser guard. */
    if (typeof indexedDB === "undefined") {
      reject(new Error("IndexedDB not available"));
      return;
    }

    const req = indexedDB.open(DB_NAME, DB_VERSION);

    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        const store = db.createObjectStore(STORE, { keyPath: "clientId" });
        store.createIndex("chatId", "chatId", { unique: false });
        store.createIndex("createdAt", "createdAt", { unique: false });
      }
    };

    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  }).catch((err) => {
    dbPromise = null;
    throw err;
  });

  return dbPromise;
}

function tx(db: IDBDatabase, mode: IDBTransactionMode) {
  return db.transaction(STORE, mode).objectStore(STORE);
}

function promisifyReq<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

export async function enqueue(entry: OutboxEntry): Promise<void> {
  try {
    const db = await openDB();
    await promisifyReq(tx(db, "readwrite").put(entry));
  } catch (err) {
    /* IDB unavailable (private mode quirks, etc.) — soft-fail.
       The send still goes through the normal HTTP path; we just lose
       persistence guarantees on this one entry. */
    console.warn("[outbox] enqueue failed:", err);
  }
}

export async function remove(clientId: string): Promise<void> {
  try {
    const db = await openDB();
    await promisifyReq(tx(db, "readwrite").delete(clientId));
  } catch (err) {
    console.warn("[outbox] remove failed:", err);
  }
}

export async function getAll(): Promise<OutboxEntry[]> {
  try {
    const db = await openDB();
    const all = await promisifyReq(tx(db, "readonly").getAll());
    return (all as OutboxEntry[]).sort((a, b) => a.createdAt - b.createdAt);
  } catch (err) {
    console.warn("[outbox] getAll failed:", err);
    return [];
  }
}

export async function getByChatId(chatId: string): Promise<OutboxEntry[]> {
  try {
    const db = await openDB();
    const store = tx(db, "readonly");
    const idx = store.index("chatId");
    const all = await promisifyReq(idx.getAll(IDBKeyRange.only(chatId)));
    return (all as OutboxEntry[]).sort((a, b) => a.createdAt - b.createdAt);
  } catch (err) {
    console.warn("[outbox] getByChatId failed:", err);
    return [];
  }
}

export async function update(
  clientId: string,
  patch: Partial<OutboxEntry>
): Promise<void> {
  try {
    const db = await openDB();
    const store = tx(db, "readwrite");
    const existing = (await promisifyReq(store.get(clientId))) as OutboxEntry | undefined;
    if (!existing) return;
    await promisifyReq(store.put({ ...existing, ...patch }));
  } catch (err) {
    console.warn("[outbox] update failed:", err);
  }
}

export async function clearAll(): Promise<void> {
  try {
    const db = await openDB();
    await promisifyReq(tx(db, "readwrite").clear());
  } catch (err) {
    console.warn("[outbox] clearAll failed:", err);
  }
}

/* Threshold past which a pending entry is marked `failed` and surfaced to the user. */
export const MAX_AUTO_ATTEMPTS = 10;
